config/routes.rb
Market::Application.routes.draw do
  root to: 'sessions#new'

  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :auctions do
     resources :bids
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
     resources :conversation_messages, as: "messages"
  end

end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Conversation < ActiveRecord::Base
   belongs_to :creator, class_name: "User", foreign_key: "user_id"
   has_many   :messages, class_name:  "ConversationMessage"
   has_many   :participations, class_name: "UserConversation", foreign_key: "conversation_id"
   has_many   :participants, through: :participations, source: :user

   validates :title, presence: true
   validates :user_id, presence: true

   after_save :add_creator_as_participant

   scope :created_by, ->(user) { where(user_id: user.id) }



   def latest_message
      messages.last.text if messages.any?
   end


   private

   def add_creator_as_participant
      participations.create(user_id: creator.id)
   end
   
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
   before_action :must_be_signed_in

   def index
      @conversations = current_user.conversations.includes(:messages)
   end

   def show
      @messages = conversation.messages.includes(:user)
      @message = ConversationMessage.new
   end

   def new
      @conversation = Conversation.new
   end

   def create
   end


   private

   def conversation
      @conversation ||= Conversation.find_by(id: params[:id])
   end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
   def must_be_part_of_conversation
      if current_user.conversations.find_by(id: params[:conversation_id]).nil?
         redirect_to signin_path, alert: "You may not do that."
      end
   end
end

app/views/conversations/_conversation.html.haml
%li
  %p= link_to conversation.title, conversation
  %p.subheader
    %small Latest message: 
  %p.subheader= conversation.latest_message
  %small
    %i.subheader= conversation.updated_at

app/views/conversations/index.html.haml
- provide(:title, "Conversations")

%h3.subheader.text-center
  Conversations

%ul.collection-list
  = render @conversations

app/views/conversations/new.html.haml
- provide(:title, "New Conversation")

= simple_form_for @conversation do |f|
  = f.input :title
  = f.input :participants

app/views/conversations/show.html.haml
.row
  .large-7.columns
    %h3.subheader.text-center
      Messages
    %ul.collection-list
      = render @messages
  .large-5.columns
    = simple_form_for @message, url: conversation_messages_path(@conversation) do |f|
      = f.input :text, label: "New Message", as: :text
      = f.submit "Submit", class: "button small success"