config/routes.rb
Market::Application.routes.draw do
  root to: 'sessions#new'

  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :auctions do
     resources :bids
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
     resources :conversation_messages, as: "messages"
  end

end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, val|
  %span{:class => "label #{key}"}
    = val

app/views/layouts/_header.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      Market
    %li.toggle-topbar.menu-icon
      %a
        %span
          Menu

  %section.top-bar-section
    %ul.right
      %li.has-dropdown
        %a Auctions
        %ul.dropdown
          %li= link_to "All", auctions_path
          %li= link_to "New", new_auction_path if signed_in?
      - if signed_in?
        %li.has-dropdown
          %a Conversations
          %ul.dropdown
            %li= link_to "Read", conversations_path
        %li= link_to "Sign out", signout_path, method: 'delete'
      - else
        %li= link_to "Sign in", signin_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
   <%= javascript_include_tag params[:controller] + "/shared" %>
   <%= javascript_include_tag params[:controller] + "/" + params[:action] %>
   <%= csrf_meta_tags %>
  </head>

  <body>

     <%= render "layouts/header" %>
     <div class="row">
        <div class="large-12 columns">
           <%= render "layouts/flash_messages" %>
        </div>
     </div>
     <div class="row">
       <div class="large-12 columns">
          <%= yield %>
       </div>
     </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>